version: '3'
services:
  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    networks:
      - conex
  receptor:
    build:
      context: .
      dockerfile: receptor/Dockerfile
    networks:
      - conex
networks:
  conex:
    driver: bridge